#ifndef ERRORS_H
#define ERRORS_H
# define SOCKET_FUNCT_FAILED 0
# define BIND_FUNCT_FAILED 1
# define LISTEN_FUNCT_FAILED 2
#define ACCEPT_FUNCT_FAILED 3
# define SOCKET_INITIALIZATION_FAILED 4
#endif // ERRORS_H
